### ISSUE TITLE
Ordering of fields

### ISSUE THREAD

**Issue by tweakitguy** [lfergon/meteor-export-csv#7]
It appears as if my mongo collection does not have an identical order of fields returned for each record that the CSV output is incorrect.

**Comment by lfergon** [comment]
So, I should add support for data on the mongo without a model data, would you prefer to have a '', null, on those positions that are not present, or just what you have on the collection?

**Comment by tweakitguy** [comment]
It doesn't appear to be an issue with null fields.  Depending on what order my data gets initialized I may have one record that appears as such:
Column 1
Column 2
Column 3

However the next item may be stored in Mongo as
Column 2
Column 1
Column 3

In this case, the CSV output data is not valid.  
| Column 1 | Column 2 | Column 3 |
| Column 2 | Column 1 | Column 3 |

I'm looking at two possible work arounds right now:
1. Make sure that all columns are initialized in Mongo collection even if no data exists
2. Attempt to re-order the collection before it is parsed into the CSV exporter

**Comment by tweakitguy** [comment]
ahh... Yes Data Model

**Comment by lfergon** [comment]
Maybe sorting the collection before parsing it: Examples.find({}, {sort: {$natural:1}});
};

**Comment by tweakitguy** [comment]
Great idea, thank you
